# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES: CI_COMMIT_SHA,CI_ENVIRONMENT_NAME,CI_ENVIRONMENT_SLUG,SEGAWAY_BUILD_USERNAME,SEGAWAY_BUILD_TOKEN

workflow:
  rules:
    - if: ($CI_MERGE_REQUEST_ID) && ($CI_PIPELINE_SOURCE != "push")
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
      
# Include AutoDevops build
include:
- local: .ci/jobs/build.gitlab-ci.yml

# Build containers for master and review
docker-build:
  extends: .ci:stage:build
  rules:
    - if: ($SEGAWAY_BUILD_USERNAME) && ($SEGAWAY_BUILD_TOKEN) && ($CI_COMMIT_BRANCH == "master") && ($CI_PIPELINE_SOURCE == "push")
      when: always
    - if: $CI_PIPELINE_SOURCE == "web"
      when: always
    - when: never

docker-review:
  extends: .ci:stage:build
  rules:
    - if: ($SEGAWAY_BUILD_USERNAME) && ($SEGAWAY_BUILD_TOKEN) && ($CI_PIPELINE_SOURCE == "merge_request_event")
      when: always
    - when: never

# Publish image to deploy registry
docker-publish:
  stage: deploy
  image: docker:19.03.12
  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
  - docker logout
  - docker login -u "$SEGAWAY_BUILD_USERNAME" -p "$SEGAWAY_BUILD_TOKEN" "$CI_REGISTRY"
  - docker pull $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA
  - docker tag $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA registry.visdev.smith-nephew.com/medical-imaging/visionaire/visdev-docker/auto-match
  - docker push registry.visdev.smith-nephew.com/medical-imaging/visionaire/visdev-docker/auto-match
