"""empty message

Revision ID: 02143b871f0b
Revises: 51db33c050d8
Create Date: 2022-05-23 08:27:54.374892-07:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02143b871f0b'
down_revision = '51db33c050d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('case_uid', sa.String(), server_default='', nullable=False),
    sa.Column('study_uid', sa.String(), server_default='', nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matching_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('email_sender', sa.String(), nullable=False),
    sa.Column('smtp_server', sa.String(), nullable=False),
    sa.Column('email_sender_password', sa.String()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('similar_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('similar_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('orthanc_no_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vcm_no_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_similar_match_id'), 'similar_match', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_similar_match_id'), table_name='similar_match')
    op.drop_table('similar_match')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
