"""add_guess_who_table

Revision ID: 127fd69b80de
Revises: 53369e779148
Create Date: 2022-07-27 14:16:41.721857-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '127fd69b80de'
down_revision = '53369e779148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guess_who',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=True),
    sa.Column('type', sa.Integer(), server_default='0', nullable=True),
    sa.Column('time', sa.Integer(), server_default='0', nullable=True),
    sa.Column('number_studies', sa.Integer(), server_default='0', nullable=True),
    sa.Column('number_cases', sa.Integer(), server_default='0', nullable=True),
    sa.Column('study_uid', sa.String(), nullable=True),
    sa.Column('number_matches', sa.Integer(), server_default='0', nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guess_who_id'), 'guess_who', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guess_who_id'), table_name='guess_who')
    op.drop_table('guess_who')
    # ### end Alembic commands ###
