"""add_guess_who_timer

Revision ID: 2da01b4410ca
Revises: 305990d5ac0b
Create Date: 2022-08-01 06:15:22.857426-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da01b4410ca'
down_revision = '305990d5ac0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('guess_who_timer', sa.Integer(), server_default='60', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'guess_who_timer')
    # ### end Alembic commands ###
