"""add_created_at_guess_who

Revision ID: 305990d5ac0b
Revises: 127fd69b80de
Create Date: 2022-07-28 09:47:52.883834-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305990d5ac0b'
down_revision = '127fd69b80de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guess_who', sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guess_who', 'created_on')
    # ### end Alembic commands ###
