"""empty message

Revision ID: 53369e779148
Revises: 714977b1419f
Create Date: 2022-07-21 10:02:38.298360-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53369e779148'
down_revision = '714977b1419f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'email_sender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('settings', 'smtp_server',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'smtp_server',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('settings', 'email_sender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
