"""New Study and Error

Revision ID: 5788170ba203
Revises: 70c2b8b24094
Create Date: 2022-05-26 07:47:01.536186-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5788170ba203'
down_revision = '70c2b8b24094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('new_study_uid', sa.String(), server_default='', nullable=True))
    op.add_column('match', sa.Column('error_reason', sa.String(), server_default='', nullable=True))
    op.alter_column('settings', 'email_sender_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('settings', 'email_sender_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('match', 'error_reason')
    op.drop_column('match', 'new_study_uid')
    # ### end Alembic commands ###
