"""add_port_settings

Revision ID: ba890d61554f
Revises: 5788170ba203
Create Date: 2022-06-06 15:21:23.636900-07:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba890d61554f'
down_revision = '5788170ba203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('email_port', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('email_internal_arrival', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email_internal_arrival')
    op.drop_column('settings', 'email_port')
    # ### end Alembic commands ###
